server:
  port: 8080

netty:
  host: 127.0.0.1
  port: 7397


# 定位模板的目录
#spring.mvc.view.prefix=classpath:/templates/
# 给返回的页面添加后缀名
#spring.mvc.view.suffix=.html
spring:
  data:
    elasticsearch:
      cluster-name: es-itstack
      cluster-nodes: 127.0.0.1:9300
      repositories:
        enabled: true
